/* eslint-disable prettier/prettier */
enum KeyCase {
  TOP_LEFT_OF_BOTTOM_LEFT,
  TOP_LEFT_OF_TOP_RIGHT,
  TOP_RIGHT_OF_TOP_LEFT,
  TOP_RIGHT_OF_BOTTOM_RIGHT,
  BOTTOM_LEFT_OF_BOTTOM_RIGHT,
  BOTTOM_LEFT_OF_TOP_LEFT,
  BOTTOM_RIGHT_OF_BOTTOM_LEFT,
  BOTTOM_RIGHT_OF_TOP_RIGHT,
}

export {KeyCase};
